//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.SanPhamKhuyenMais = new HashSet<SanPhamKhuyenMai>();
        }

        [Display(Name = "ID Khuyến mãi")]
        public int IDKhuyenMai { get; set; }

        [Display(Name = "Tên khuyến mãi")]
        [Required(ErrorMessage ="Tên khuyến mãi là bắt buộc.")]
        public string TenKhuyenMai { get; set; }

        [Required(ErrorMessage = "Ngày bắt đầu là bắt buộc.")]
        [Display(Name = "Ngày bắt đầu")]
        public Nullable<System.DateTime> NgayBatDau { get; set; }

        [Required(ErrorMessage = "Ngày kết thúc là bắt buộc.")]
        [Display(Name = "Ngày kết thúc")]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }

        [Required(ErrorMessage = "Phần trăm giảm là bắt buộc.")]
        [Display(Name = "Phần trăm giảm")]
        public Nullable<decimal> PhanTramGiam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamKhuyenMai> SanPhamKhuyenMais { get; set; }
    }
}
