//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.DanhGias = new HashSet<DanhGia>();
            this.GioHangs = new HashSet<GioHang>();
            this.SanPhamKhuyenMais = new HashSet<SanPhamKhuyenMai>();
        }

        [Display(Name = "ID Sản Phẩm")]
        public int IDSanPham { get; set; }

        [Required(ErrorMessage = "Tên Sản Phẩm là bắt buộc")]
        [Display(Name = "Tên Sản Phẩm")]
        public string TenSanPham { get; set; }

        [Required(ErrorMessage = "Mô Tả là bắt buộc")]
        [Display(Name = "Mô Tả")]
        public string MoTa { get; set; }

        [Required(ErrorMessage = "Giá là bắt buộc")]
        [Range(0, double.MaxValue, ErrorMessage = "Giá phải là một giá trị dương")]
        [Display(Name = "Giá bán")]
        public Nullable<decimal> Gia { get; set; }

        [Display(Name = "Trạng Thái")]
        public Nullable<bool> TrangThai { get; set; }

        [Display(Name = "Số Lượng Tồn")]
        public Nullable<int> SoLuongTon { get; set; }

        [Display(Name = "Hình Ảnh")]
        public string HinhAnh { get; set; }

        [Display(Name = "Loại Sản Phẩm")]
        public Nullable<int> IDLoaiSP { get; set; }

        [Display(Name = "Nhà Cung Cấp")]
        public Nullable<int> IDNhaCungCap { get; set; }

        [Display(Name = "Ngày Tạo")]
        public Nullable<System.DateTime> NgayTao { get; set;  }

        [Display(Name = "Đơn Vị Tính")]
        public string DonViTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamKhuyenMai> SanPhamKhuyenMais { get; set; }
    }
}
