//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPhamKhuyenMai
    {

        [Display(Name = "ID sản phẩm")]
        public int IDSanPham { get; set; }

        [Display(Name = "ID khuyến mãi")]
        public int IDKhuyenMai { get; set; }

        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
