//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteNongSan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThanhToan
    {
        public int IDThanhToan { get; set; }

        [Display(Name = "Phương thức thanh toán")]
        public string PhuongThuc { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public decimal TongTienThanhToan { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> IDDonHang { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
